Repository SAP/spartacus, pull requests merged in 2018-11, with the labels that each got.

#38 Speed up CI
  .travis.yml
  build.sh
  ci-scripts/e2e-tests.sh
  ci-scripts/lint.sh
  ci-scripts/other.sh
  ci-scripts/unit-tests.sh
Labels: review request > ca, team/poland, type/enhancementrequest

#142 Registration E2E / SPA-1021
  projects/storefrontapp-e2e/src/suites/register.e2e-spec.ts
Labels: epic/e2etests, team/poland

#36 E2E test for added-to-cart modal / SPA-839
  projects/storefrontapp-e2e/src/page-objects/cmslib/added-to-cart-modal.po.ts
  projects/storefrontapp-e2e/src/suites/added-to-cart-modal.e2e-spec.ts
  projects/storefrontapp-e2e/src/suites/big-happy-path.e2e-spec.ts
  projects/storefrontapp-e2e/src/suites/cart.e2e-spec.ts
  projects/storefrontapp-e2e/src/suites/currency.e2e-spec.ts
Labels: epic/e2etests, team/poland

#50 Add to Home & Move PWA config out of the application - Feature/spa 1394
  .gitignore
  angular.json
  projects/storefrontapp/src/app/app.module.ts
  projects/storefrontapp/src/assets/icons/icon-128x128.png
  projects/storefrontapp/src/assets/icons/icon-144x144.png
  projects/storefrontapp/src/assets/icons/icon-152x152.png
  projects/storefrontapp/src/assets/icons/icon-192x192.png
  projects/storefrontapp/src/assets/icons/icon-384x384.png
  projects/storefrontapp/src/assets/icons/icon-512x512.png
  projects/storefrontapp/src/assets/icons/icon-72x72.png
  projects/storefrontapp/src/assets/icons/icon-96x96.png
  projects/storefrontapp/src/index.html
  projects/storefrontapp/src/manifest.json
  projects/storefrontlib/src/lib/pwa/add-to-home-screen-btn/add-to-home-screen-btn.component.html
  projects/storefrontlib/src/lib/pwa/add-to-home-screen-btn/add-to-home-screen-btn.component.spec.ts
  projects/storefrontlib/src/lib/pwa/add-to-home-screen-btn/add-to-home-screen-btn.component.ts
  projects/storefrontlib/src/lib/pwa/ngsw-config.json
  projects/storefrontlib/src/lib/pwa/pwa.module-config.ts
  projects/storefrontlib/src/lib/pwa/pwa.module.ts
  projects/storefrontlib/src/lib/storefront-config.ts
  projects/storefrontlib/src/lib/ui/layout/header/header.component.spec.ts
  projects/storefrontlib/src/lib/ui/layout/header/header.module.ts
  projects/storefrontlib/src/lib/ui/layout/header/mobile-menu/mobile-menu.component.html
  projects/storefrontlib/src/lib/ui/layout/header/mobile-menu/mobile-menu.component.scss
  projects/storefrontlib/src/lib/ui/layout/header/mobile-menu/mobile-menu.component.spec.ts
  projects/storefrontlib/src/lib/ui/layout/main/storefront.component.spec.ts
  projects/storefrontlib/src/public_api.ts
Labels: epic/addtohome, review request > ca, team/poland

#201 #148: Handle modal close events
  projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/shipping-address/address-form/address-form.component.ts
Labels: team/poland, type/bug

#175 Feature/spa 1164 - From Sandbox: UI Order History styling
  projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/container/multi-step-checkout.component.scss
  projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/shipping-address/address-form/address-form.component.html
  projects/storefrontlib/src/lib/my-account/order/order-history/order-history.component.scss
  projects/storefrontstyles/scss/ybase/blocks/forms.scss
Labels: team/gladiators

#164 #45 Product Details E2E / SPA-1026
  projects/storefrontapp-e2e/src/page-objects/product-details.po.ts
  projects/storefrontapp-e2e/src/suites/product-details.e2e-spec.ts
Labels: epic/e2etests, team/asterix

#237 Feature/#227 CxApi module for grouping facade services
  projects/storefrontlib/src/lib/cx-api/cx-api.module.ts
  projects/storefrontlib/src/lib/cx-api/cx-api.service.spec.ts
  projects/storefrontlib/src/lib/cx-api/cx-api.service.ts
  projects/storefrontlib/src/lib/cx-api/index.ts
  projects/storefrontlib/src/lib/storefront.module.ts
  projects/storefrontlib/src/public_api.ts
Labels: comp: core, epic/facades, team/framed

#254 GH-253: Add cxApi to cxApi input of web component
  projects/storefrontlib/src/lib/cms/components/dynamic-slot/component-wrapper.directive.spec.ts
  projects/storefrontlib/src/lib/cms/components/dynamic-slot/component-wrapper.directive.ts
  projects/storefrontlib/src/lib/cms/services/component-mapper.service.spec.ts
  projects/storefrontlib/src/lib/cms/services/component-mapper.service.ts
Labels: team/framed

#215 #184 first part of implementation
  projects/core/src/config/config.module.ts
  projects/core/src/routing/configurable-routes/configurable-route.ts
  projects/core/src/routing/configurable-routes/configurable-routes-config.ts
  projects/core/src/routing/configurable-routes/configurable-routes.module.spec.ts
  projects/core/src/routing/configurable-routes/configurable-routes.module.ts
  projects/core/src/routing/configurable-routes/configurable-routes.service.spec.ts
  projects/core/src/routing/configurable-routes/configurable-routes.service.ts
  projects/core/src/routing/configurable-routes/index.ts
  projects/core/src/routing/configurable-routes/routes-config-loader.spec.ts
  projects/core/src/routing/configurable-routes/routes-config-loader.ts
  projects/core/src/routing/configurable-routes/routes-config.ts
  projects/core/src/routing/index.ts
  projects/core/src/routing/routing.module.ts
  projects/storefrontlib/src/lib/storefront-config.ts
  projects/storefrontlib/src/lib/ui/layout/main/storefront.component.spec.ts
  projects/storefrontlib/src/lib/ui/layout/main/storefront.component.ts
  projects/storefrontlib/src/lib/ui/pages/product-page/product-page.module.ts
Labels: epic/routes, team/framed

#363 Fix GH-362
  .prettierignore
Labels: epic/config, epic/routing
