Repository SAP/spartacus, pull requests merged in 2018-12, with the labels that each got.

#453 GH-452 E2EC-1288 Show spinner when choosing view all stores in store finder
  projects/storefrontlib/src/lib/store-finder/components/store-finder-store-description/store-finder-store-description.component.html
  projects/storefrontlib/src/lib/store-finder/components/store-finder-store-description/store-finder-store-description.component.spec.ts
  projects/storefrontlib/src/lib/store-finder/components/store-finder-store-description/store-finder-store-description.component.ts
  projects/storefrontlib/src/lib/store-finder/components/store-finder-stores-count/store-finder-stores-count.component.html
  projects/storefrontlib/src/lib/store-finder/components/store-finder-stores-count/store-finder-stores-count.component.ts
  projects/storefrontlib/src/lib/store-finder/store/reducers/find-stores.reducer.ts
  projects/storefrontlib/src/lib/store-finder/store/reducers/view-all-stores.reducer.spec.ts
  projects/storefrontlib/src/lib/store-finder/store/reducers/view-all-stores.reducer.ts
  projects/storefrontlib/src/lib/store-finder/store/selectors/view-all-stores.selectors.spec.ts
  projects/storefrontlib/src/lib/store-finder/store/selectors/view-all-stores.selectors.ts
Labels: epic/storefinder, pr review, team/asterix, team/walkers

#704 GH-702: Complette success flag support for product
  projects/core/src/product/facade/product.service.spec.ts
  projects/core/src/product/facade/product.service.ts
  projects/core/src/product/store/selectors/product.selectors.spec.ts
  projects/core/src/product/store/selectors/product.selectors.ts
  projects/core/src/state/utils/entity-loader/entity-loader.reducer.spec.ts
  projects/core/src/state/utils/entity-loader/entity-loader.reducer.ts
  projects/core/src/state/utils/entity-loader/entity-loader.selectors.spec.ts
  projects/core/src/state/utils/entity-loader/entity-loader.selectors.ts
  projects/core/src/state/utils/entity/entity.reducer.ts
  projects/core/src/state/utils/loader/loader.reducer.spec.ts
  projects/core/src/state/utils/loader/loader.reducer.ts
  projects/core/src/state/utils/loader/loader.selectors.spec.ts
Labels: team/framed

#701 GH-700 E2EC-1174 Get store for store-description from backend
  projects/storefrontlib/src/lib/occ/store/store-finder.service.spec.ts
  projects/storefrontlib/src/lib/occ/store/store-finder.service.ts
  projects/storefrontlib/src/lib/store-finder/components/store-finder-store-description/store-finder-store-description.component.html
  projects/storefrontlib/src/lib/store-finder/components/store-finder-store-description/store-finder-store-description.component.spec.ts
  projects/storefrontlib/src/lib/store-finder/components/store-finder-store-description/store-finder-store-description.component.ts
  projects/storefrontlib/src/lib/store-finder/services/store-finder.service.spec.ts
  projects/storefrontlib/src/lib/store-finder/services/store-finder.service.ts
  projects/storefrontlib/src/lib/store-finder/store/actions/find-stores.action.spec.ts
  projects/storefrontlib/src/lib/store-finder/store/actions/find-stores.action.ts
  projects/storefrontlib/src/lib/store-finder/store/effects/find-stores.effect.spec.ts
  projects/storefrontlib/src/lib/store-finder/store/effects/find-stores.effect.ts
  projects/storefrontlib/src/lib/store-finder/store/reducers/find-stores.reducer.spec.ts
  projects/storefrontlib/src/lib/store-finder/store/reducers/find-stores.reducer.ts
Labels: epic/storefinder, team/walkers

#768 GH-731 - Error when clicking store finder link
  projects/storefrontlib/src/lib/ui/pages/store-finder-page/store-finder-page.module.ts
Labels: team/asterix
