Repository SAP/spartacus, pull requests merged in 2020-11, with the labels that each got.

#9430 feat: directive to dismiss or close active modal
  projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.module.ts
  projects/storefrontlib/src/cms-components/cart/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.html
  projects/storefrontlib/src/cms-components/cart/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.spec.ts
  projects/storefrontlib/src/cms-components/cart/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.ts
  projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.html
  projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.spec.ts
  projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.ts
  projects/storefrontlib/src/cms-components/cart/cart-shared/cart-shared.module.ts
  projects/storefrontlib/src/shared/components/modal/index.ts
  projects/storefrontlib/src/shared/components/modal/modal.directive.spec.ts
  projects/storefrontlib/src/shared/components/modal/modal.directive.ts
  projects/storefrontlib/src/shared/components/modal/modal.module.ts
Labels: hacktoberfest-accepted

#9732 chore: migration for removed properties of LoginFormComponent and removed redirect behavior
  docs/migration/3_0.md
  projects/schematics/src/migrations/3_0/methods-and-properties-deprecations/data/login-form.component.migration.ts
  projects/schematics/src/migrations/3_0/methods-and-properties-deprecations/methods-and-properties-deprecations.ts
  projects/schematics/src/shared/constants.ts
Labels: blocks-RC

#9730 chore: migration for StockNotificationComponent
  docs/migration/3_0.md
  projects/schematics/src/migrations/3_0/constructor-deprecations/constructor-deprecations.ts
  projects/schematics/src/migrations/3_0/constructor-deprecations/data/stock-notification.component.migration.ts
  projects/schematics/src/shared/constants.ts
Labels: blocks-RC

#9840 chore: Migrations fix for latest CDC changes
  docs/migration/3_0.md
  projects/schematics/src/migrations/3_0/constructor-deprecations/data/cdc-auth.service.migration.ts
Labels: blocks-RC

#9945 chore: Fixes for storefinder migrations
  docs/migration/3_0.md
  projects/schematics/src/migrations/3_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
  projects/schematics/src/shared/constants.ts
Labels: blocks-RC, migration, migration-docs
